### ISSUE TITLE
[Question] API 응답(에러) 응답값 처리 방식 관련  

### ISSUE THREAD

**Issue by esyeol** [dinos-dev/dinos#12]
안녕하세요~ 프론트에서 API 에러 응답값을 처리할 때, 백엔드에서 반환하는 응답 값을 그대로 화면에 보여줄 것인지, 아니면 새롭게 작성된 응답 포맷을 사용할 것인지에 대해 논의가 필요합니다. 지금 아래 작성된 처리방식에서 1번 방식으로 진행을 하고 있었는데, 2번 방식이 더 나은 방식이라고 생각되어서 제안드립니다.

1. **백엔드에서 반환하는 에러 응답값을 그대로 프론트에서 사용**:
   - 이 방식은 백엔드에서 반환하는 에러 메시지나 세부적인 에러 정보를 그대로 화면에 보여주는 방법입니다.
   - 하지만, 이렇게 하면 **두 분이 개발하시면서 어떤 에러인지 정확하게 파악하기 어려울 수 있습니다**. 특히, **특정 에러 응답값을 통해 에러의 종류를 유추**할 수 있을 때 **보안상 문제가 될 수** 있습니다.

2. **백엔드 에러 응답을 별도로 가공하여 프론트에서 사용**:
   - 백엔드에서 반환하는 에러 포맷을 **디테일하게 작성한 후**, 이를 **프론트에서 사용자에게 보여주기 적합한 형태로 변환**하여 사용합니다.
   - 이렇게 작업을 할 경우 **백엔드에서 발생하는 에러의 세부 사항을 프론트에 직접 전달하지 않기 때문에 보안상 더 안전**할 수 있습니다. 
   - 현재 스웨거 문서 구조도 제가 미리 정의한 HTTP 에러 포맷 양식을 그냥 추가만 해주면 되는 방식이라 작업도 더 단축될 수 있습니다.

제 생각에는 백엔드에서 **에러 포맷은 디테일하게 작성하되**, **에러의 정의**는 두 분이 협의 후 **각 에러에 대해 적합한 응답 포맷을 정리**해두고, 이를 화면에 표시하는 형태로 진행하는 것이 좋을 것 같습니다.

내용 확인하시고 괜찮은 의견 있으시면 답변 부탁드립니다!😀

**Comment by iziz9** [comment]
1번 방식대로 서버 응답값을 그대로 사용하면 사용자가 에러 상황에서 벗어나기 위해 뭘 해야 하는지 표시해줄 수 없는 추가적인 문제가 있습니다.
말씀하신 것 처럼 프론트에서 에러 종류에 따라 응답 포맷을 정의해두고, 
**'페이지 접근 권한이 없습니다. 로그인해주세요.'** 와 같이 
[**에러 발생 알림 + 사용자가 수행해야 할 동작**]을 함께 표시해주는 방식이 더 적절할 것 같습니다..!

**Comment by mingyu0711** [comment]
저도 2번 방식이 더 좋아 보입니다. 백엔드에서 에러에 대한 응답을 정의하면 관리하는 측면에서도 복잡할 것 같고 추후 수정할때도 백엔드를 다시 배포해야 될텐데 백엔드 보단 프론트에서 배포를 하는게 나아 보이고 메시지에 대한 정의도 디테일하게 관리할 수 있을 것 같습니다

**Comment by esyeol** [comment]
> 1번 방식대로 서버 응답값을 그대로 사용하면 사용자가 에러 상황에서 벗어나기 위해 뭘 해야 하는지 표시해줄 수 없는 추가적인 문제가 있습니다. 말씀하신 것 처럼 프론트에서 에러 종류에 따라 응답 포맷을 정의해두고, **'페이지 접근 권한이 없습니다. 로그인해주세요.'** 와 같이 [**에러 발생 알림 + 사용자가 수행해야 할 동작**]을 함께 표시해주는 방식이 더 적절할 것 같습니다..!

넵! 의견 감사합니다😊

**Comment by esyeol** [comment]
> 저도 2번 방식이 더 좋아 보입니다. 백엔드에서 에러에 대한 응답을 정의하면 관리하는 측면에서도 복잡할 것 같고 추후 수정할때도 백엔드를 다시 배포해야 될텐데 백엔드 보단 프론트에서 배포를 하는게 나아 보이고 메시지에 대한 정의도 디테일하게 관리할 수 있을 것 같습니다

넵! 의견 감사합니다😊
